version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3011:3011"
    env_file:
      - ".env"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
